#include <iostream>
#include <cstdlib>
#include <ctime>
using namespace std;

int main() {
	srand(time(NULL));
	int min_n { 1 }, max_n { 10 }, n { 0 }, guess { 0 }, lives { 0 },
			base_lives { 0 }, multiplier { 1 }, comp_score { 0 }, player_score {
					0 }, round { 1 }, level { 1 };
	bool alive { 0 }, hint { 0 }, play { 0 };

	cout << "Let's play \"Guess my number\"!" << endl << endl;
	cout << "Rules of the game:" << endl;
	cout << "You are trying to guess the number generated by the computer"
			<< endl;
	cout << "You start every round with a certain number of lives" << endl;
	cout << "Every guess will cost you 1 life." << endl;
	cout << "If you guess wrong, you will be offered a hint." << endl;
	cout << "Taking the hint will also cost you 1 life." << endl;
	cout << "If you guess the number correctly, you win a round" << endl;
	cout
			<< "If you run out of lives, you lose the round and computer will get score"
			<< endl;
	cout
			<< "If you have more points than the computer after 3 rounds you get to level 2."
			<< endl;
	cout << "After 2 rounds on level 2, the game is over. Whoever has more points wins" << endl;
	cout << endl;
	cout << "Do you want to play?" << endl;
	cout << "0 to exit, anything else to play" << endl;
	cin >> play;

	while (play) {
		cout << "Level " << level << ", round " << round << "." << endl;
		if (level == 1) {
			min_n = 1;
			max_n = 10;
		} else if (level == 2) {
			min_n = 10;
			max_n = 100;
		}
		cout << "Try to guess my number between " << min_n << " and " << max_n
				<< "!" << endl;
		lives = (min_n + max_n) / 2 / level;
		base_lives = lives;
		multiplier = level * 5;
		alive = (lives > 0);
		n = min_n + rand() % (max_n - min_n + 1);

		while (alive) {
			cout << "You are alive" << endl;
			cout << "You have " << lives << " lives left" << endl;
			cout << "Enter your guess" << endl;
			cin >> guess;
			if (guess == n) {
				break;
			} else {
				lives--;
				cout << "Wrong guess! Do you want a hint?" << endl;
				cout << "0 to refuse, anything else to take" << endl;
				cin >> hint;
				if (hint) {
					lives--;
					cout << "My number is "
							<< ((n < guess) ? "lesser" : "greater")
							<< " than your guess" << endl;
				}
				cout << endl;
			}

			alive = (lives > 0);
		}

		if (alive) {
			cout << endl;
			player_score += lives * multiplier;
			cout << "Congratulations! You've guessed the number " << n
					<< " correctly" << endl;
			cout << "You've finished the round with " << lives << " lives."
					<< endl;
		} else {
			comp_score += base_lives * multiplier;
			cout
					<< "Sorry, you're dead. You've run out of lives before guessing the number "
					<< n << endl;
		}
		cout << "Your score after " << round << " round(s) is " << player_score
				<< endl;
		cout << "Computer's score is " << comp_score << endl;
		if (level == 2 && round == 2) {
			cout << "You've played all the rounds you can in this game" << endl;
			if (player_score >= comp_score)
				cout << "You've won the game";
			else
				cout << "You've lost the game";
			cout << endl;
			cout << "Do you want to start over?" << endl;
			cout << "0 to exit, anything else to play" << endl;
			cin >> play;
			if (play) {
				level = 1;
				round = 1;
				player_score = 0;
				comp_score = 0;
			} else {
				return 0;
			}
		} else if (level == 1 && round == 3) {
			if (player_score >= comp_score) {
				level++;
				round = 0;
			} else {
				cout
						<< "Your score is less than computer's score after 3 rounds"
						<< endl;
				cout << "Do you want to start over?" << endl;
				cout << "0 to exit, anything else to play" << endl;
				cin >> play;
				if (play) {
					level = 1;
					round = 1;
					player_score = 0;
					comp_score = 0;
				} else {
					return 0;
				}
			}
		}
		cout << "Do you want to play another round?" << endl;
		cout << "0 to exit, anything else to play" << endl;
		cin >> play;
		if (play) {
			round++;
		}
	}

	return 0;
}
